### ISSUE TITLE
Still Active or?

### ISSUE THREAD

**Issue by airboss001** [SpoonX/aurelia-orm#313]
Hi Roberto,
Was looking to see if this is still planned to be maintained or if you have moved on with other exciting projects since it appears to not have been touched for some time.
Thank you, either way still an interesting project.

**Comment by RWOverdijk** [comment]
@airboss001 It hasn't been touched in a while because it simply works :) I do spend more time on our Node.js ORM, that's true. But as far as the browser ORM is concerned, this works fine. I'm working a lot with React + React Native nowadays, so I don't spend a lot of time on the Aurelia plugins.

@doktordirk does though, and others use it a lot. More than 100 installs in a week, without updates, tells me that it's still alive and kicking.

I hope this answers your question! 🍻

**Comment by airboss001** [comment]
Thanks for the response.
And good news about the project.
Sometimes its hard to tell if it is abandoned, or just (as you note) works.
