### ISSUE TITLE
How to handle nested resources

### ISSUE THREAD

**Issue by MarcScheib** [SpoonX/aurelia-orm#41]
Hi guys,

I have a question regarding nested resources. I have an article with multiple comments. I get the article via `GET /articles/{id}` and the corresponding comments via `GET /articles/{id}/comments` (the id is retrieved via a URL param).

The first GET is no problem (`entityManager.getRepository('article')` and `find(params.id)``). How would I handle the second GET? Right now, I am doing a``find(params.id + '/comments')`` on the articles repo. This does not look correct so far, am I missing something here from the docs?

Now, the same for adding a comment. My resource is `POST /articles/{id}/comments`. How would I handle the dynamic param id in the comment entity?

Thank you for your help. Btw you are doing nice work here.

**Comment by RWOverdijk** [comment]
Hello @MarcScheib,

Good question. I haven't gotten into this situation yet because I use populate, or criteria. For the time being, what should work is `entityManager.getRepository('comments').find({article: articleId})`. Or (if you're using sails) it should populate the comments on your article for you automatically.

**Comment by RWOverdijk** [comment]
@MarcScheib I'm closing this issue. But if you still have any questions, feel free to comment!
