### ISSUE TITLE
add resetEntity

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-orm#84]
there shouldn't be the need to store originals oneself

**Comment by RWOverdijk** [comment]
There should. I want to know what changed. It's also useful for maintaining relationships :)

**Comment by doktordirk** [comment]
actually i found they are stored

``` js
this.__cleanValues = {
      checksum: JSON.stringify(cleanValues),
      data: cleanValues
    };
```

so adding a resetData(){  this.setData(this.__cleanValues.data); } does not seem to harm

**Comment by RWOverdijk** [comment]
Except that it does also store the associations, which is difficult to reset. I think I have an idea for this.

**Comment by doktordirk** [comment]
as for the tiltle. yeah, that would be stupid. i'll rename it

**Comment by pfurini** [comment]
@doktordirk Actually, for entity properties (not associations) we should do:

```
if (!this.isNew()) {
  this.setData(this.__cleanValues.data.entity);
  this.markClean();
}
```

because `__cleanValues.data` has an `entity` and `collections` sub properties.
The code above works great when no relations are involved, and I'm using it for simple entities.

**UPDATE**: added check for new entity in the code snippet
